### ISSUE TITLE
Scorewindows

### ISSUE THREAD

**Issue by djangobaer** [hugbug/conpianist#41]
After loading one of my midi the following error was in the scoreframe:
![image](https://user-images.githubusercontent.com/62076869/76704683-02db0300-66db-11ea-9b6e-58b26ae77968.png)

The song ist working but no scores are shown. By reducing to 8 channels all is working well.

![image](https://user-images.githubusercontent.com/62076869/76704698-12f2e280-66db-11ea-836a-ca182a6ccf5a.png)

So, the programm should have only that channels in scoreframe you want to play. At least 1 and 2, because I take all the the channels I want to play at 1 and 2 using MixMaster.

Only for information.
Harald

**Comment by hugbug** [comment]
The error message means the page height isn't enough to display the score. Maximising of window may help (if it isn't maximised yet). Otherwise when creating the MusicXml-file you can leave only instruments you need (but keep everything in your MIDI).

> So, the programm should have only that channels in scoreframe you want to play. 

Yes, created a separate issue for that. This issue however has a low priority because there is a workaround.

**Comment by djangobaer** [comment]
Ok, I will try that.
